# -*- coding: utf-8 -*-
"""LIMS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8Rd4sVPZFs7w8prFzBtw8EBepQhdaTv
"""

!pip install streamlit

import streamlit as st
import pandas as pd
from datetime import date

# 1. Configuración de la página
st.set_page_config(page_title="LIMS Resistencia", layout="wide")

# 2. Los 12 antibióticos de tu lista
atbs = ['AMP', 'CIP', 'FEP', 'CRO', 'CAZ', 'CZO', 'ETP', 'FOS', 'GEN', 'MEM', 'NOR', 'TMP']

st.title("🔬 Registro de Antibiograma")
st.markdown("---")

# 3. Formulario de Entrada
with st.form("form_lims"):
    col_info1, col_info2 = st.columns(2)
    with col_info1:
        id_muestra = st.text_input("🆔 ID de Muestra / Código Paciente")
    with col_info2:
        fecha = st.date_input("📅 Fecha de Proceso", date.today())

    st.write("### 🧫 Resultados del Panel (S/I/R)")

    # Creamos 4 columnas para que queden 3 antibióticos por fila (4x3=12)
    cols = st.columns(4)
    resultados = {}

    for i, atb in enumerate(atbs):
        with cols[i % 4]:
            resultados[atb] = st.selectbox(f"**{atb}**", ["S", "I", "R"], key=atb)

    st.markdown("---")
    submitted = st.form_submit_button("💾 Guardar Panel Completo")

    if submitted:
        if id_muestra:
            # Crear el diccionario de datos
            datos = {"ID": [id_muestra], "Fecha": [fecha]}
            datos.update({k: [v] for k, v in resultados.items()})

            df = pd.DataFrame(datos)
            st.success(f"✅ Muestra {id_muestra} registrada.")
            st.dataframe(df) # Muestra cómo quedó la fila
        else:
            st.error("⚠️ Por favor, ingresa un ID de muestra.")



from google.colab import drive
drive.mount('/content/drive')

pip install st-gsheets-connection

import streamlit as st
from streamlit_gsheets import GSheetsConnection
import pandas as pd
from datetime import date

st.set_page_config(page_title="LIMS RAM", layout="wide")

# Conexión con Google Sheets (Sustituye por el link de tu hoja)
url = "https://drive.google.com/file/d/13jfBryqSa6Lb9u7pYxsfccwhvAly8-9z/view?usp=sharing"
conn = st.connection("gsheets", type=GSheetsConnection)

atbs = ['AMP', 'CIP', 'FEP', 'CRO', 'CAZ', 'CZO', 'ETP', 'FOS', 'GEN', 'MEM', 'NOR', 'TMP']

st.title("🔬 LIMS - Registro de Resistencia")

# Formulario
with st.form("registro"):
    c1, c2 = st.columns(2)
    id_muestra = c1.text_input("ID Muestra")
    fecha = c2.date_input("Fecha", date.today())

    st.write("### Antibióticos")
    cols = st.columns(4)
    res = {}
    for i, atb in enumerate(atbs):
        with cols[i % 4]:
            res[atb] = st.selectbox(atb, ["S", "I", "R"], key=atb)

    boton = st.form_submit_button("Guardar en la Nube")

    if boton:
        if id_muestra:
            # Crear nueva fila
            nueva_fila = pd.DataFrame([{
                "ID": id_muestra,
                "Fecha": str(fecha),
                **res
            }])

            # Leer datos actuales y añadir la nueva fila
            try:
                existente = conn.read(spreadsheet=url)
                actualizado = pd.concat([existente, nueva_fila], ignore_index=True)
                conn.update(spreadsheet=url, data=actualizado)
                st.success("✅ Datos guardados en Google Sheets")
            except Exception as e:
                st.error(f"Error: {e}")
        else:
            st.warning("Escribe el ID de la muestra")

if res['MEM'] == 'R' or res['ETP'] == 'R':
    st.warning("⚠️ ALERTA: Posible Carbapenemasa detectada. Verificar cepa.")

st.markdown("---")
st.header("📊 Histórico de Resultados")

# Botón para refrescar los datos desde la nube
if st.button("Actualizar Historial"):
    try:
        df_historico = conn.read(spreadsheet=url)

        # Filtro rápido por ID de Muestra
        busqueda = st.text_input("🔍 Buscar por ID de Muestra")
        if busqueda:
            df_historico = df_historico[df_historico['ID'].str.contains(busqueda, case=False)]

        st.dataframe(df_historico, use_container_width=True)

        # Pequeña estadística rápida
        st.subheader("📈 Resumen de Resistencia")
        atb_analizar = st.selectbox("Selecciona un antibiótico para ver estadística:", atbs)
        conteo = df_historico[atb_analizar].value_config()
        st.bar_chart(conteo)

    except Exception as e:
        st.info("Aún no hay datos guardados o la hoja está vacía.")

# Ejemplo de alerta de multirresistencia
if res['MEM'] == 'R' and res['ETP'] == 'R' and res['CIP'] == 'R':
    st.error("🚨 ALERTA: Perfil de multirresistencia detectado (Carbapenémicos + Quinolonas).")